version: '3'
services:
    pici:
      build: .
      container_name: pici
      ports: 
        - "2222:22"
      volumes:
        - "docker:/var/lib/docker/"
      image: lucas42/pici
      privileged: true
      restart: always

volumes:
  docker: