version: 2.1
orbs:
  lucos: lucos/deploy@0
workflows:
  version: 2
  build-deploy:
    jobs:
      - lucos/build-arm64:
          context: docker
      - lucos/deploy-salvare:
          context: docker
          requires:
            - lucos/build-arm64
          filters:
            branches:
              only:
                - main
      - lucos/build-armv7l:
          context: docker
      - lucos/deploy-xwing:
          context: docker
          requires:
            - lucos/build-armv7l
          filters:
            branches:
              only:
                - main